# 1. Connexion à la base de données (Vérifiez bien le port 5433)
spring.datasource.url=jdbc:postgresql://localhost:5433/fintech_db
spring.datasource.username=postgres
spring.datasource.password=sabali

# 2. Indispensable pour PostgreSQL : définit le dialecte Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 3. Création automatique des tables
spring.jpa.hibernate.ddl-auto=update

# 4. Affichage du SQL pour le débogage (Utile pour vos examens)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# 4. Optionnel : Pour éviter les conflits de port (si 8080 est déjà pris)
server.port=8082